const testWrapper=document.querySelector(".test-wrapper");const testArea=document.querySelector("#test-area");const resetButton=document.querySelector("#reset");const theTimer=document.querySelector(".timer");var wpmDisplay=document.querySelector("#wpm");var typingErrorDisplay=document.querySelector("#errors");var accuracyDisplay=document.querySelector("#accuracy");var changeOriginText=document.querySelector("#alter");var wordCountDisplay=document.querySelector("#wordcount");var manyText=["Click anywhere on this box to change the text you are taking your speed typing test with! The text in this box is your typing test text. All tests are great for practice. Including this informational text. Practice, practice, practice! All of the following text's including this one are available for the speed typing test and can be looped through until you reach the desired text you wish to take the speed typing test against.","This is a typing test. Your goal is to duplicate the provided text, EXACTLY, in the field below. The timer starts when you start typing, and only stops when you match this text exactly. Do your best now. Good Luck!","Do not lose time on daily trivialities. Do not dwell on petty detail, for all these things melt away and drift apart within the obscure traffic of time. Live well and live broadly. You are alive and living now. Now is the envy of all of the dead.","Hello world. It is a nice day.","The 1910 Cuba hurricane was said to be one of the worst tropical cyclones that has ever hit Cuba. The storm formed in the southern carribbean sea on October 9, 1910.","It grew stronger as it moved northwest. It then made landfall on the western end of Cuba. The storm made a loop over open water, and then began moving towards the United States.","I love writing stories! Especially when I get to write about difficult situations for the protagonist. Since then I can make him YELL in frustration or HOWL in pain. Every story needs conflict and resolution. How much conflict and how often can determine the tone and pacing of your story. Pay careful attention to the way you construct your stories otherwise even a strong plot can feel empty if the pacing is poor. Character growth can be important but your characters should have obvious shortcomings, otherwise you risk creating a character who doesn't feel very real. Go, craft unique stories!"];var arrCount=0;var timer=[0,0,0,0];var interval;var timerRunning=!1;var wordsPerMinCalc;var typingError=0;var accuracy;var wordCount=0;window.onload=function(){switchText()};function switchText(){if(timer[2]>=1){alert("cannot change text during test! If you wish to change test text you must reset the timer.")}else{changeOriginText.innerHTML=manyText[arrCount];getWordCount(manyText,arrCount);if(arrCount>=manyText.length){arrCount=0}
reset();}}
function getWordCount(text,arrayCount){var containerArray=manyText[arrCount];var separate;if(changeOriginText.innerHTML===containerArray){for(var i=0;i<containerArray.length;i++){separate=containerArray.split(" ");break}}
wordCount=separate.length;return wordCount}
function leadingZero(time){if(time<=9){time="0"+time}
return time}
function runTimer(){let currentTime=leadingZero(timer[0])+":"+leadingZero(timer[1])+":"+leadingZero(timer[2]);theTimer.innerHTML=currentTime;timer[3]++;timer[0]=Math.floor((timer[3]/100)/60);timer[1]=Math.floor((timer[3]/100)-(timer[0]*60));timer[2]=Math.floor(timer[3]-(timer[1]*100)-(timer[0]*6000))}
function spellCheck(){let textEntered=testArea.value;let originTextMatch=changeOriginText.innerHTML.substring(0,textEntered.length);if(textEntered==changeOriginText.innerHTML){clearInterval(interval);testWrapper.style.borderColor="#008000";if(timer[0]>=1){var completeTime=timer[0]+(timer[1]/60);wordsPerMinCalc=Math.round(wordCount/completeTime)}else{var accurateMeasure=timer[1]/60;wordsPerMinCalc=Math.round(wordCount/accurateMeasure)}
wpmDisplay.innerHTML=wordsPerMinCalc;accuracy=Math.round(((wordCount-typingError)/wordCount)*100);accuracyDisplay.innerHTML=accuracy+"%"}else{if(textEntered==originTextMatch){testWrapper.style.borderColor="#65CCf3"}else{typingError++;typingErrorDisplay.innerHTML=typingError;testWrapper.style.borderColor="#8B0000"}}}
function start(){let textEnteredLength=testArea.value.length;wordCountDisplay.innerHTML=wordCount;if(textEnteredLength===0&&!timerRunning){timerRunning=!0;interval=setInterval(runTimer,10)}}
function reset(){clearInterval(interval);interval=null;timer=[0,0,0,0];timerRunning=!1;wordsPerMinCalc=0;typingError=0;accuracy=0;testArea.value="";theTimer.innerHTML="00:00:00";testWrapper.style.borderColor="grey";wpmDisplay.innerHTML="---";typingErrorDisplay.innerHTML="---";accuracyDisplay.innerHTML="---";wordCountDisplay.innerHTML="---"}
testArea.addEventListener("keypress",start,!1);testArea.addEventListener("keyup",spellCheck,!1);resetButton.addEventListener("click",reset,!1);changeOriginText.addEventListener("click",switchText,!1);